<?php

/**
 * This is the model base class for the table "barrio".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Barrio".
 *
 * Columns in table "barrio" available as properties of the model,
 * followed by relations of table "barrio" available as properties of the model.
 *
 * @property integer $id
 * @property string $nombre
 * @property integer $ciudad_id
 *
 * @property Ciudad $ciudad
 * @property Direccion[] $direccions
 */
abstract class BaseBarrio extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'barrio';
    }

    public static function representingColumn() {
        return 'nombre';
    }

    public function rules() {
        return array(
            array('nombre', 'required'),
            array('ciudad_id', 'numerical', 'integerOnly'=>true),
            array('nombre', 'length', 'max'=>32),
            array('ciudad_id', 'default', 'setOnEmpty' => true, 'value' => null),
            array('id, nombre, ciudad_id', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'ciudad' => array(self::BELONGS_TO, 'Ciudad', 'ciudad_id'),
            'direccions' => array(self::HAS_MANY, 'Direccion', 'barrio_id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'nombre' => Yii::t('app', 'Nombre'),
                'ciudad_id' => Yii::t('app', 'Ciudad'),
                'ciudad' => null,
                'direccions' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('nombre', $this->nombre, true);
        $criteria->compare('ciudad_id', $this->ciudad_id);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}