<?php

/**
 * This is the model base class for the table "ciudad".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Ciudad".
 *
 * Columns in table "ciudad" available as properties of the model,
 * followed by relations of table "ciudad" available as properties of the model.
 *
 * @property integer $id
 * @property string $nombre
 * @property integer $provincia_id
 *
 * @property Barrio[] $barrios
 * @property Provincia $provincia
 * @property Cliente[] $clientes
 */
abstract class BaseCiudad extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'ciudad';
    }

    public static function representingColumn() {
        return 'nombre';
    }

    public function rules() {
        return array(
            array('nombre, provincia_id', 'required'),
            array('provincia_id', 'numerical', 'integerOnly'=>true),
            array('nombre', 'length', 'max'=>32),
            array('id, nombre, provincia_id', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'barrios' => array(self::HAS_MANY, 'Barrio', 'ciudad_id'),
            'provincia' => array(self::BELONGS_TO, 'Provincia', 'provincia_id'),
            'clientes' => array(self::HAS_MANY, 'Cliente', 'ciudad_id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'nombre' => Yii::t('app', 'Nombre'),
                'provincia_id' => Yii::t('app', 'Provincia'),
                'barrios' => null,
                'provincia' => null,
                'clientes' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('nombre', $this->nombre, true);
        $criteria->compare('provincia_id', $this->provincia_id);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}